name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-mlds-landing-page:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
    #Checkout on repo
    - uses: actions/checkout@v3
    #Install node
    - name: Install node modules
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    #Install npm dependecies
    - run: npm i
    - run: npm ci
    #Action for build and push the image
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image mlds-landing-page
      with:
        image: unjudge/mlds-landing-page
        tags: latest
        registry: docker.io
        directory: ./
        dockerfile: ./Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        